### ISSUE TITLE
Custom variables overwritten

### ISSUE THREAD

**Issue by XioNoX** [jloh/nagios-nrpe-server#18]
Because of:

```
- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"
```

If I set for example:

```
nagios_nrpe_server_plugins_dir: /usr/lib/nagios/plugins/custom
```

In my vars files (not in the role's var file).

My custom value will be overwritten by the default one.

**Comment by jloh** [comment]
Interesting, I'd never thought of this! It should be possible to move this into the `defaults` section but I'll have to confirm.

**Comment by jloh** [comment]
I'm not sure how to fix this one. Ideally I'd be able to include the variables pragmatically like I do now but within the `defaults` dir. Sadly this isn't the case.

I could split them all our into separate variables on a per-OS level but this isn't as pretty as the current solution.

If I added another `include` step for custom variables overwrites after the main include would that work?
