### ISSUE TITLE
Ansible role for the latest nrpe-server 3.0.1 and nagios-plugins 2.2.0 version

### ISSUE THREAD

**Issue by kaushalshriyan** [jloh/nagios-nrpe-server#21]
Hi James,

We have the latest version of nrpe 3.x (https://www.nagios.org/news/2016/09/nrpe-3-0-1-released/) and nagios-plugins 2.2.0. (https://nagios-plugins.org/nagios-plugins-2-2-0-released/). I will appreciate if you can point me the Ansible role for the latest nrpe and nagios-plugin versions as mentioned above.

Once again thanks in advance.

Regards,

Kaushal

**Comment by jloh** [comment]
Has the config format changed in 3.x? I'm not sure I fully understand what you mean.

This role should install the latest version of both `nrpe` and `nagios-plugins` that are available for your OS.

**Comment by kaushalshriyan** [comment]
Hi James,

The current installed versions on the server are quite old. The latest version of nrpe 3.x (https://www.nagios.org/news/2016/09/nrpe-3-0-1-released/) and nagios-plugins 2.2.0. (https://nagios-plugins.org/nagios-plugins-2-2-0-released/). I will appreciate if you can include the latest version in the Ansible role. 

[root@localhost plugins]# pwd
/usr/lib64/nagios/plugins
[root@localhost plugins]# ./check_nagios  --help
check_nagios v2.1.4 (nagios-plugins 2.1.4)
Copyright (c) 1999-2014 Nagios Plugin Development Team
	<devel@nagios-plugins.org>

This plugin checks the status of the Nagios process on the local machine
The plugin will check to make sure the Nagios status log is no older than
the number of minutes specified by the expires option.
It also checks the process table for a process matching the command argument.


Usage:
check_nagios -F <status log file> -t <timeout_seconds> -e <expire_minutes> -C <process_string>

Options:
 -h, --help
    Print detailed help screen
 -V, --version
    Print version information
 --extra-opts=[section][@file]
    Read options from an ini file. See
    https://www.nagios-plugins.org/doc/extra-opts.html
    for usage and examples.
 -F, --filename=FILE
    Name of the log file to check
 -e, --expires=INTEGER
    Minutes aging after which logfile is considered stale
 -C, --command=STRING
    Substring to search for in process arguments
 -t, --timeout=INTEGER
    Timeout for the plugin in seconds
 -v, --verbose
    Show details for command-line debugging (Nagios may truncate output)

Examples:
 check_nagios -t 20 -e 5 -F /usr/local/nagios/var/status.log -C /usr/local/nagios/bin/nagios

Send email to help@nagios-plugins.org if you have questions regarding use
of this software. To submit patches or suggest improvements, send email to
devel@nagios-plugins.org

[root@localhost plugins]# rpm -qa | grep nagios
nagios-common-4.2.4-2.el7.x86_64
nagios-plugins-ircd-2.1.4-2.el7.x86_64
nagios-plugins-nt-2.1.4-2.el7.x86_64
nagios-plugins-ups-2.1.4-2.el7.x86_64
nagios-plugins-icmp-2.1.4-2.el7.x86_64
nagios-plugins-ssh-2.1.4-2.el7.x86_64
nagios-plugins-tcp-2.1.4-2.el7.x86_64
nagios-plugins-real-2.1.4-2.el7.x86_64
nagios-plugins-load-2.1.4-2.el7.x86_64
nagios-plugins-ide_smart-2.1.4-2.el7.x86_64
nagios-plugins-dig-2.1.4-2.el7.x86_64
nagios-plugins-ntp-perl-2.1.4-2.el7.x86_64
nagios-plugins-snmp-2.1.4-2.el7.x86_64
nagios-plugins-fping-2.1.4-2.el7.x86_64
nagios-plugins-perl-2.1.4-2.el7.x86_64
nagios-plugins-file_age-2.1.4-2.el7.x86_64
nagios-plugins-breeze-2.1.4-2.el7.x86_64
nagios-plugins-wave-2.1.4-2.el7.x86_64
nagios-plugins-http-2.1.4-2.el7.x86_64
nagios-plugins-log-2.1.4-2.el7.x86_64
nagios-plugins-nagios-2.1.4-2.el7.x86_64
nagios-plugins-dhcp-2.1.4-2.el7.x86_64
nagios-plugins-time-2.1.4-2.el7.x86_64
nagios-plugins-smtp-2.1.4-2.el7.x86_64
nagios-plugins-procs-2.1.4-2.el7.x86_64
nagios-plugins-dummy-2.1.4-2.el7.x86_64
nagios-plugins-users-2.1.4-2.el7.x86_64
nagios-plugins-disk-2.1.4-2.el7.x86_64
nagios-plugins-nwstat-2.1.4-2.el7.x86_64
nagios-plugins-overcr-2.1.4-2.el7.x86_64
nagios-plugins-ldap-2.1.4-2.el7.x86_64
nagios-plugins-ntp-2.1.4-2.el7.x86_64
nagios-plugins-mrtgtraf-2.1.4-2.el7.x86_64
nagios-plugins-pgsql-2.1.4-2.el7.x86_64
nagios-plugins-mysql-2.1.4-2.el7.x86_64
nagios-plugins-dns-2.1.4-2.el7.x86_64
nagios-plugins-disk_smb-2.1.4-2.el7.x86_64
nagios-plugins-sensors-2.1.4-2.el7.x86_64
nagios-plugins-2.1.4-2.el7.x86_64
nagios-plugins-flexlm-2.1.4-2.el7.x86_64
nagios-plugins-mailq-2.1.4-2.el7.x86_64
nagios-plugins-mrtg-2.1.4-2.el7.x86_64
nagios-plugins-cluster-2.1.4-2.el7.x86_64
nagios-plugins-ping-2.1.4-2.el7.x86_64
nagios-plugins-swap-2.1.4-2.el7.x86_64
nagios-plugins-oracle-2.1.4-2.el7.x86_64
nagios-plugins-by_ssh-2.1.4-2.el7.x86_64
nagios-plugins-hpjd-2.1.4-2.el7.x86_64
nagios-plugins-rpc-2.1.4-2.el7.x86_64
nagios-plugins-game-2.1.4-2.el7.x86_64
nagios-plugins-all-2.1.4-2.el7.x86_64
#rpm -qa | grep nrpe
nrpe-2.15-7.el7.x86_64
#ps aux | grep nrpe
nrpe      7667  0.0  0.0  44188  1384 ?        Ss   14:35   0:00 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d
root      9229  0.0  0.0 112648   952 pts/2    S+   16:21   0:00 grep --color=auto nrpe

/usr/sbin/nrpe

NRPE - Nagios Remote Plugin Executor
Copyright (c) 1999-2008 Ethan Galstad (nagios@nagios.org)
Version: 2.15
Last Modified: 09-06-2013
License: GPL v2 with exemptions (-l for more info)
SSL/TLS Available: Anonymous DH Mode, OpenSSL 0.9.6 or higher required
TCP Wrappers Available

***************************************************************
** POSSIBLE SECURITY RISK - COMMAND ARGUMENTS ARE SUPPORTED! **
**      Read the NRPE SECURITY file for more information     **
***************************************************************

Usage: nrpe [-n] -c <config_file> [-4|-6] <mode>

Options:
 -n            = Do not use SSL
 <config_file> = Name of config file to use
 -4            = use ipv4 only
 -6            = use ipv6 only
 <mode>        = One of the following operating modes:
   -i          =    Run as a service under inetd or xinetd
   -d          =    Run as a standalone daemon
   -d -s       =    Run as a subsystem under AIX

Notes:
This program is designed to process requests from the check_nrpe
plugin on the host(s) running Nagios.  It can run as a service
under inetd or xinetd (read the docs for info on this), or as a
standalone daemon. Once a request is received from an authorized
host, NRPE will execute the command/plugin (as defined in the
config file) and return the plugin output and return code to the
check_nrpe plugin.
# cat /etc/nagios/nrpe.cfg
#############################################################################
# Sample NRPE Config File
# Written by: Ethan Galstad (nagios@nagios.org)
#
# **Last Modified: 11-23-2007**
#
# NOTES:
# This is a sample configuration file for the NRPE daemon.  It needs to be
# located on the remote host that is running the NRPE daemon, not the host
# from which the check_nrpe client is being executed.
#############################################################################

# LOG FACILITY
# The syslog facility that should be used for logging purposes.

log_facility=daemon

# PID FILE
# The name of the file in which the NRPE daemon should write it's process ID
# number.  The file is only written if the NRPE daemon is started by the root
# user and is running in standalone mode.

pid_file=/var/run/nrpe/nrpe.pid

# PORT NUMBER
# Port number we should wait for connections on.
# NOTE: This must be a non-priviledged port (i.e. > 1024).
# NOTE: This option is ignored if NRPE is running under either inetd or xinetd

server_port=5666

# SERVER ADDRESS
# Address that nrpe should bind to in case there are more than one interface
# and you do not want nrpe to bind on all interfaces.
# NOTE: This option is ignored if NRPE is running under either inetd or xinetd

#server_address=127.0.0.1

# NRPE USER
# This determines the effective user that the NRPE daemon should run as.
# You can either supply a username or a UID.
#
# NOTE: This option is ignored if NRPE is running under either inetd or xinetd

nrpe_user=nrpe

# NRPE GROUP
# This determines the effective group that the NRPE daemon should run as.
# You can either supply a group name or a GID.
#
# NOTE: This option is ignored if NRPE is running under either inetd or xinetd

nrpe_group=nrpe

# ALLOWED HOST ADDRESSES
# This is an optional comma-delimited list of IP address or hostnames
# that are allowed to talk to the NRPE daemon. Network addresses with a bit mask
# (i.e. 192.168.1.0/24) are also supported. Hostname wildcards are not currently
# supported.
#
# Note: The daemon only does rudimentary checking of the client's IP
# address.  I would highly recommend adding entries in your /etc/hosts.allow
# file to allow only the specified host to connect to the port
# you are running this daemon on.
#
# NOTE: This option is ignored if NRPE is running under either inetd or xinetd

allowed_hosts=172.16.214.8,127.0.0.1

# COMMAND ARGUMENT PROCESSING
# This option determines whether or not the NRPE daemon will allow clients
# to specify arguments to commands that are executed.  This option only works
# if the daemon was configured with the --enable-command-args configure script
# option.
#
# *** ENABLING THIS OPTION IS A SECURITY RISK! ***
# Read the SECURITY file for information on some of the security implications
# of enabling this variable.
#
# Values: 0=do not allow arguments, 1=allow command arguments

dont_blame_nrpe=0

# BASH COMMAND SUBTITUTION
# This option determines whether or not the NRPE daemon will allow clients
# to specify arguments that contain bash command substitutions of the form
# $(...).  This option only works if the daemon was configured with both
# the --enable-command-args and --enable-bash-command-substitution configure
# script options.
#
# *** ENABLING THIS OPTION IS A HIGH SECURITY RISK! ***
# Read the SECURITY file for information on some of the security implications
# of enabling this variable.
#
# Values: 0=do not allow bash command substitutions,
#         1=allow bash command substitutions

allow_bash_command_substitution=0

# COMMAND PREFIX
# This option allows you to prefix all commands with a user-defined string.
# A space is automatically added between the specified prefix string and the
# command line from the command definition.
#
# *** THIS EXAMPLE MAY POSE A POTENTIAL SECURITY RISK, SO USE WITH CAUTION! ***
# Usage scenario:
# Execute restricted commmands using sudo.  For this to work, you need to add
# the nagios user to your /etc/sudoers.  An example entry for alllowing
# execution of the plugins from might be:
#
# nagios          ALL=(ALL) NOPASSWD: /usr/lib/nagios/plugins/
#
# This lets the nagios user run all commands in that directory (and only them)
# without asking for a password.  If you do this, make sure you don't give
# random users write access to that directory or its contents!

# command_prefix=/usr/bin/sudo

# DEBUGGING OPTION
# This option determines whether or not debugging messages are logged to the
# syslog facility.
# Values: 0=debugging off, 1=debugging on

debug=0

# COMMAND TIMEOUT
# This specifies the maximum number of seconds that the NRPE daemon will
# allow plugins to finish executing before killing them off.

command_timeout=60

# CONNECTION TIMEOUT
# This specifies the maximum number of seconds that the NRPE daemon will
# wait for a connection to be established before exiting. This is sometimes
# seen where a network problem stops the SSL being established even though
# all network sessions are connected. This causes the nrpe daemons to
# accumulate, eating system resources. Do not set this too low.

connection_timeout=300

# WEEK RANDOM SEED OPTION
# This directive allows you to use SSL even if your system does not have
# a /dev/random or /dev/urandom (on purpose or because the necessary patches
# were not applied). The random number generator will be seeded from a file
# which is either a file pointed to by the environment valiable $RANDFILE
# or $HOME/.rnd. If neither exists, the pseudo random number generator will
# be initialized and a warning will be issued.
# Values: 0=only seed from /dev/[u]random, 1=also seed from weak randomness

#allow_weak_random_seed=1

# INCLUDE CONFIG FILE
# This directive allows you to include definitions from an external config file.

#include=<somefile.cfg>

# INCLUDE CONFIG DIRECTORY
# This directive allows you to include definitions from config files (with a
# .cfg extension) in one or more directories (with recursion).

#include_dir=<somedirectory>
#include_dir=<someotherdirectory>

# COMMAND DEFINITIONS
# Command definitions that this daemon will run.  Definitions
# are in the following format:
#
# command[<command_name>]=<command_line>
#
# When the daemon receives a request to return the results of <command_name>
# it will execute the command specified by the <command_line> argument.
#
# Unlike Nagios, the command line cannot contain macros - it must be
# typed exactly as it should be executed.
#
# Note: Any plugins that are used in the command lines must reside
# on the machine that this daemon is running on!  The examples below
# assume that you have plugins installed in a /usr/local/nagios/libexec
# directory.  Also note that you will have to modify the definitions below
# to match the argument format the plugins expect.  Remember, these are
# examples only!

# The following examples use hardcoded command arguments...

command[check_users]=/usr/lib64/nagios/plugins/check_users -w 5 -c 10
command[check_load]=/usr/lib64/nagios/plugins/check_load -w 15,10,5 -c 30,25,20
command[check_hda1]=/usr/lib64/nagios/plugins/check_disk -w 20% -c 10% -p /dev/hda1
command[check_zombie_procs]=/usr/lib64/nagios/plugins/check_procs -w 5 -c 10 -s Z
command[check_total_procs]=/usr/lib64/nagios/plugins/check_procs -w 150 -c 200

# The following examples allow user-supplied arguments and can
# only be used if the NRPE daemon was compiled with support for
# command arguments *AND* the dont_blame_nrpe directive in this
# config file is set to '1'.  This poses a potential security risk, so
# make sure you read the SECURITY file before doing this.

#command[check_users]=/usr/lib64/nagios/plugins/check_users -w $ARG1$ -c $ARG2$
#command[check_load]=/usr/lib64/nagios/plugins/check_load -w $ARG1$ -c $ARG2$
#command[check_disk]=/usr/lib64/nagios/plugins/check_disk -w $ARG1$ -c $ARG2$ -p $ARG3$
#command[check_procs]=/usr/lib64/nagios/plugins/check_procs -w $ARG1$ -c $ARG2$ -s $ARG3$

#
# local configuration:
# if you'd prefer, you can instead place directives here
include=/etc/nagios/nrpe_local.cfg
include=/etc/nagios/nrpe_ansible.cfg

#
# you can place your config snipplets into nrpe.d/
# only snipplets ending in .cfg will get included
include_dir=/etc/nagios/nrpe.d/

**Comment by jloh** [comment]
@kaushalshriyan what OS are you using?

**Comment by shriyankaushal** [comment]
@jloh  

I am using CentOS Linux release 7.3.1611 (Core)
[root@localhost ~]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[root@localhost ~]#

**Comment by shriyankaushal** [comment]
@jloh Checking in if you need any additional information from me.

**Comment by jloh** [comment]
If you have a look at the [changelog](https://github.com/NagiosEnterprises/nrpe/blob/0ffd219ce004bd91ba0c0d2db291ec51545ca8fb/Changelog) for NRPE you can see that the changes between your currently running version and the latest just aren't that huge. Not to mention this would require manually compiling the NRPE and nagios-plugins packages.

Manually compiling packages vs using the system ones is a pretty big responsibility to take on and not something I'm interesting into merging into this role at this point in time unfortunately. You're more than welcome to custom compile the packages yourself and continue to use this role to manage NRPE.

Unless you have a requirement to use the latest version of NRPE/Nagios plugins I would be extremely hesitant to compile it yourself.

P.S: did you change accounts or something there?
